### PR TITLE
install sccache in the image

### PR DESCRIPTION
**Pull request by cbeck88**
Hi, would you take a patch to install sccache in the image? It's pretty useful for making builds faster

`cargo install sccache` builds `sccache` from source, which is simple, but it's slower and idk if that is bad for you. We could also download pre-built packages, up to your preference

```
# Define the sccache version
ARG SCCACHE_VERSION=0.3.0

ENV SCCACHE_URL="https://github.com/mozilla/sccache/releases/download/v${SCCACHE_VERSION}/sccache-v${SCCACHE_VERSION}-x86_64-unknown-linux-musl.tar.gz"
#SCCACHE_URL="https://github.com/mozilla/sccache/releases/download/v${SCCACHE_VERSION}/sccache-v${SCCACHE_VERSION}-aarch64-unknown-linux-musl.tar.gz"

# Install prebuilt sccache based on platform
RUN wget -O sccache.tar.gz $SCCACHE_URL && \
    tar -xzf sccache.tar.gz && \
    mv sccache-v${SCCACHE_VERSION}-*-unknown-linux-musl/sccache /usr/local/bin/ && \
    chmod +x /usr/local/bin/sccache && \
    rm -rf sccache.tar.gz sccache-v${SCCACHE_VERSION}-*-unknown-linux-musl
```

### CODE REVIEW

**Comment by clux** [comment]
Hey, thanks for this. I think `sccache` is probably one of those tools that make a lot of sense in this image.

The tradeoff here would mostly be compile times (which are already [taking an hour on GHA](https://github.com/clux/muslrust/actions/workflows/stable.yml) due to arm)), so my gut feel here is that installing via `curl` by grabbing the right tarball in each image build from the [releases](https://github.com/mozilla/sccache/releases), would probably be the best thing to try. If you're able to try that out, I'd take a patch!

**Comment by cbeck88** [comment]
this is passing tests for me locally, lmk if it looks okay. thanks

**Comment by clux** [comment]
Thanks a lot! This looks sensible to me. Happy to include it as is, but two questions in case they are not oversights:

- we are both downloading the binary and cargo installing it? is that intended?
- we seem to be pinning 0.3.0, but see we have 0.8.0 in https://github.com/mozilla/sccache/releases

**Comment by cbeck88** [comment]
Sorry, that’s a mistake, will fix

**Review by clux — APPROVED** [review]
Thank you. Happy to send this out as is for now.
If you have some usage you could link in the future in this issue or in the README then this would be appreciated!

**Pull request merged**
