### PR TITLE
GitHub actions for stable

### PR DESCRIPTION
**Pull request by AnderEnder**

### CODE REVIEW

**Comment by clux** [comment]
hey there. i would like to have this automated as well, but i need some api call to figure out if there's a new stable release (can't just do a periodic every 6 weeks due to the patch releases).

if you're able to find something that can do that i can help get this in automatically!

**Comment by clux** [comment]
oh, it looks like you're doing a fork, nevermind :-)

**Comment by AnderEnder** [comment]
@clux, I am playing around with static build and jemalloc, so accidentally created a PR to master repo.
But I am happy to help you with this automation as well.

**Comment by clux** [comment]
Ah cool. Yeah, people are complaining about allocators with musl :|
Would be interesting to see if you get that working.

Have raised #71 for my separate issue.

**Pull request closed without merging**
