### PR TITLE
arm draft verify

### PR DESCRIPTION
**Pull request by clux**
for #133

### CODE REVIEW

**Comment by clux** [comment]
hm, am i doing something wrong 🤔 
 
```
# on mac after doing just build-stable-arm and testing with the arm64 test params
./test/plaincrate/target/aarch64-unknown-linux-musl/debug/plaincrate
zsh: exec format error: ./test/plaincrate/target/aarch64-unknown-linux-musl/debug/plaincrate
```

**Comment by eranrund** [comment]
> hm, am i doing something wrong 🤔
> 
> ```
> # on mac after doing just build-stable-arm and testing with the arm64 test params
> ./test/plaincrate/target/aarch64-unknown-linux-musl/debug/plaincrate
> zsh: exec format error: ./test/plaincrate/target/aarch64-unknown-linux-musl/debug/plaincrate
> ```

I think that's expected - Mac can't run Linux binaries even if they're both ARM64.

**Comment by clux** [comment]
I guess that makes sense. Don't know why I expected that to work.

It's ultimately cloud environments where musl is most useful in `arm` land so not a big problem.

**Comment by eranrund** [comment]
Looks like this just passed CI - was there anything else you wanted to do here?

**Comment by clux** [comment]
I'll run a quick sanity tomorrow against an arm environment, but locally this looks good!

**Comment by clux** [comment]
@eranrund all good. have a full e2e in https://github.com/kube-rs/version-rs/pull/93

(i did also struggle with using cargo run with --platform in https://github.com/kube-rs/controller-rs/pull/67 where it bombs out, but that's probably something else - and i am happy that i can at least use the builder pattern)

**Pull request closed without merging**
